### ISSUE TITLE
respect auditing_enabled

### ISSUE THREAD

**Issue by courtsimas** [leonardofalk/audited_async#5]
If auditing is disabled for a specific model or for system wide for all audits, this async gem doesn't respect that and will still audit.

**Comment by leonardofalk** [comment]
Gonna take a while untill I check this one, it shouldn't be a problem though, the default job is calling `write_audit`, which according to [this line](https://github.com/collectiveidea/audited/blob/master/lib/audited/auditor.rb#L308) skips auditing when disabled.

**Comment by leonardofalk** [comment]
@courtsimas The problem was after sending write_audit to the job, the block value of `auditing_enabled` is lost. Fixed in 0.2.2, thanks for the heads up.
